### ISSUE TITLE
新版SunUI界面问题

### ISSUE THREAD

**Issue by SaintOsiris** [Coolkids/SunUI#126]
C大，新版的SunUI已经安装，非常不错
目前游戏过程中发现两件事
1.聊天频道没有快捷标签，也无法通过TAB切换。
2.小地图旁没有日历按钮

若能添加，感激不尽

**Comment by Coolkids** [comment]
1.已经做了
2.点右下角的时间 如果没有再重新开个issue 此issue3天后关闭
