### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yclwll** [Coolkids/SunUI#128]
...rface\AddOns\ElvUI_SunUI_Module\core\skins_sunui.lua:156: attempt to call method 'IsEnabled' (a nil value)
Count: 12

Call Stack:
[C](?): in function `IsEnabled'
...rface\AddOns\ElvUI_SunUI_Module\core\skins_sunui.lua:156: in function <...rface\AddOns\ElvUI_SunUI_Module\core\skins_sunui.lua:155>

**Comment by Coolkids** [comment]
在哪里遇到的?
怎么重现?
